config/routes.rb
Rails.application.routes.draw do
  get 'cart/index'
  devise_for :users
  resources :books

  # GET cart/
  get 'cart/', to: "cart#index", as: :carts

  # GET carts/sold
  get 'cart/sold', to: "cart#sold", as: :sold

  # GET books/cart/add/:id
  get 'cart/buy_book/:id', to: "cart#buy_book", as: :buy_book

  # GET carts/remove
  delete 'cart/return_book/:id', to: "cart#return_book", as: :return_book

  # GET carts/api/
  get 'carts/api', to: "cart#carts_api"

  # GET books/api/books/all
  get 'books/api/books/all', to: "books#getAllBooks"

  # GET /books/my/uploads
  get '/books/my/uploads', to: "books#uploads", as: :uploads

  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user, foreign_key: 'user_id'
  has_one_attached :image, dependent: :destroy
  validates :year, :title, :author, presence: true

  has_many :carts, dependent: :destroy
  has_many :users, through: :carts

  # def image_url
  #   Rails.application.routes.url_helpers.url_for(image) if image.attached?
  # end

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :book, foreign_key: 'book_id'
end

app/models/user.rb
class User < ApplicationRecord

  has_many :books, dependent: :destroy

  has_many :carts, dependent: :destroy
  has_many :books, through: :carts

  validates :username, uniqueness: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :full_name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :full_name, :email, :password, :current_password)}
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy buy_book remove_book ]

  before_action :authenticate_user!, except: %i[ index show getAllBooks ]
  # before_action :correct_user, only: %i[ edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all.with_attached_image
  end

  # books/cart/add/:id
  def buy_book
    puts "add book #{@book.title}"
    @cart = Cart.new(user_id: current_user.id, book_id: params[:id])
    respond_to do |format|
      if @cart.save
        @book.update_column(:is_sold, true)
        format.html { render :buy_book }
      end
    end
  end

  # books/cart/remove/:id
  def remove_book
    puts "remove book #{@book.title}"
    @cart = Cart.where(book_id: @book.id)
    @cart.destroy!
    @book.update_column(:is_sold, false)
  end

  # GET books/api/books/all
  def getAllBooks
    @books = []
    if params[:search].present?
      search = params[:search]
      if search == ""
        @books = get_books
      else
        @books = Book.where(is_sold: false).where('title Like ? OR author Like ?', "%#{search}%", "%#{search}%" ).with_attached_image
      end
    else
      @books = get_books
    end
    render json: @books.map { |book|
        if book.image.attached?
          book.as_json.merge({ image: url_for(book.image) })
        else
          book.as_json.merge({ image: :null })
        end
    }
  end

  def get_books
    @books = Book.where(is_sold: false).with_attached_image
  end

  # getting

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /books/my/uploads
  def uploads
    if params[:query].present?
      if params[:query] == 'sold'
        @books = Book.where(user_id: current_user.id).where(is_sold: true)
        elsif params[:query] == 'not-sold'
        @books = Book.where(user_id: current_user.id).where(is_sold: false)

      elsif params[:query] == 'all-books'
        @books = Book.where(user_id: current_user.id)
      end
    else
      @books = Book.where(user_id: current_user.id)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, :author, :price, :genre, :year, :image, :user_id)
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!

  def index
    @carts = Cart.where(user_id: current_user.id).joins(:book).includes(:book)
  end

  def sold
    @carts = Cart.joins(:book, :user).includes(:book, :user).where(books: { user_id: current_user.id })
  end

  def buy_book
    @book = Book.find(params[:id])
    @cart = Cart.new(user_id: current_user.id, book_id: params[:id])
    respond_to do |format|
      if @cart.save
        @book.update_column(:is_sold, true)
        format.html { render :buy_book }
      end
    end
  end

  def return_book
    @cart = Cart.joins(:book, :user).includes(:book, :user).where(book_id: params[:id]).where(user_id: current_user.id).first
    @cart.destroy!
    @book = Book.find(params[:id])
    @book.update_column(:is_sold, false)
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@cart.book)}_item") }
    end
  end

  def carts_api
    @carts = Cart.where(user_id: 4).joins(:book).includes(:book)
    render json: @carts.to_json(include: [:book, :user])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/books/_book.html.erb
<%# main container %>
<div class="width-large flex-row center-flex">
  <%#   width %>
  <div class="width-md-1 flex-col flex-gap">
    <%# header %>
    <section class="width-large flex-row center-flex-y flex-space-between" >
      <h5> <%= book.title %> </h5>
      <%# <button class="btn btn-success"> Buy This Book </button> %>
      <% if book.user_id != current_user.id %>
        <%= turbo_frame_tag "btn-change" do %>
          <%= link_to "Buy this book", buy_book_path(book), class: 'btn btn-success' %>
        <% end %>
      <% else %>
        <span class="badge text-bg-danger">This Your Book</span>
      <% end %>
    </section>
    <%# body %>
    <div class="flex-row flex-gap book-description-row">
      <div class="">
        <%# image %>
        <% if book.image.attached? %>
          <% if book.image.image? %>
            <%= image_tag book.image, class: 'image-size' %>
          <% end %>
        <% else %>
          <img class="image-size " src="https://images.template.net/174732/free-story-book-cover-template-edit-online.jpg" alt="">
        <% end %>
      </div>
      <section class="flex-col pad ">
        <%# description %>
        <span> <%= book.price %> </span>
        <span> <%= book.year.year %> - <%= book.genre %> </span>
        <span> <%= book.author %> </span>
        <p> <%= book.description %> </p>
      </div>
      <%# responsive  %>
      <div class="flex-col book-description-col flex-gap center-flex-y">
        <div class="">
          <%# image %>
          <% if book.image.attached? %>
            <% if book.image.image? %>
              <%= image_tag book.image, class: 'image-size' %>
            <% end %>
          <% else %>
            <img class="image-size " src="https://images.template.net/174732/free-story-book-cover-template-edit-online.jpg" alt="">
          <% end %>
        </div>
        <section class="flex-col width-large pad align-flex-start">
          <%# description %>
          <span> <%= book.price %> </span>
          <span> <%= book.year.year %> - <%= book.genre %> </span>
          <span> <%= book.author %> </span>
          <p> <%= book.description %> </p>
        </div>
      </div>
    </div>

app/views/books/_card.html.erb
<div class="book-item">
  <img class="item-image" src="https://images.template.net/174732/free-story-book-cover-template-edit-online.jpg" alt="">
  <a href="#">
    <div class="flex-col full-size pad">
      <span class="height-main"> Title </span>
      <div class="flex-col">
        <span> Author  </span>
        <span> 2012 - Horror  </span>
      </div>
    </div>
  </a>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book, class: 'row g-3 needs-validation') do |form| %>
  <% if book.errors.any? %>
    <div class="alert alert-danger pad" role="alert">
      <ul class="error-ul">
        <% book.errors.each do |error| %>
          <li> <%= error.full_message %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-12">
    <% if is_edit %>
      <% if book.image.attached? %>
        <% if book.image.image? %>
          <%= image_tag book.image, class: 'image-size' %>
        <% end %>
      <% else %>
        <img class="image-size " src="https://images.template.net/174732/free-story-book-cover-template-edit-online.jpg" alt="">
      <% end %>
    <% end %>
  </div>
  <%# title %>
  <div class="col-md-6">
    <%= form.label :title, class:"form-label", for:"validationCustom01" %>
    <%= form.text_field :title, class:"form-control", id:"validationCustom01", required:true, placeholder: 'Book Title' %>
  </div>
  <%# author %>
  <div class="col-md-6">
    <%= form.label :author,class:"form-label", for:"validationCustom01"  %>
    <%= form.text_field :author, class:"form-control", id:"validationCustom01", required:true, placeholder: 'Book Author' %>
  </div>
  <%# description %>
  <div class="col-md-12">
    <%= form.label :description, class:"form-label", for:"validationCustom01" %>
    <%= form.text_area :description, class:"form-control", id:"validationCustom01", placeholder: 'Book Description' %>
  </div>
  <%# genre %>
  <div class="col-md-6">
    <%= form.label :genre, class:"form-label", for:"validationCustom01" %>
    <%= form.text_field :genre, class:"form-control", id:"validationCustom01", required:true, placeholder: 'Book Genre' %>
  </div>
  <%# year %>
  <div class="col-md-6">
    <%= form.label :year, class:"form-label", for:"validationCustom01"%>
    <%= form.date_field :year, class:"form-control", id:"validationCustom01", required:true %>
  </div>
  <%# price %>
  <div class="col-md-6">
    <%= form.label :price, class:"form-label", for:"validationCustom01" %>
    <%= form.text_field :price, type: :number, class:"form-control", id:"validationCustom01", required:true, placeholder: 'Book Price' %>
  </div>
  <%# image %>
  <div class="col-md-6">
    <%= form.label :image, class:"form-label", for:"validationCustom01" %>
    <%= form.file_field :image, class:"form-control", id:"validationCustom01" %>
  </div>
  <%= form.text_field :user_id, value: current_user.id, type: :hidden %>
  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/books/_row.html.erb
<tr>
  <th scope="row">1</th>
  <td><%= book.title %></td>
  <td><%= book.author %></td>
  <td><%= book.genre %></td>
  <td><%= book.year %></td>
  <td><%= book.price %></td>
  <td>
    <%= link_to book_path(book), class: 'btn btn-sm btn-info' do %>
      <i class="bi bi-eye"></i> Show
    <% end %>
    <%= link_to edit_book_path(book), class: 'btn btn-sm btn-primary' do %>
      <i class="bi bi-pencil-fill"></i>  Edit
    <% end %>
    <%= link_to book_path(book),  data: { "turbo-method": :delete }, class: 'btn btn-sm btn-danger' do %>
      <i class="bi bi-trash-fill"></i>  Delete
    <% end %>
  </td>
</tr>

app/views/books/_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Book Title</th>
      <th scope="col">Book Author</th>
      <th scope="col">Book Genre</th>
      <th scope="col">Book Year</th>
      <th scope="col">Book Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <%= render 'row', book: book  %>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="width-large flex-row center-flex ">
  <div class="width-md-1 center-flex flex-col flex-gap">
    <div class="flex-row flex-space-between width-large">
      <H4>Editing book</H4>
      <%= link_to "Back to uploads", uploads_path, class: 'btn btn-secondary left-arrow' %>
    </div>
    <%= render "form", book: @book, is_edit: true %>
    <div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div id="books" class="width-large pad-0 flex-col center-flex">
  <div class="width-md-1 flex-col flex-gap">
    <div class="flex-row flex-space-between center-flex-y">
      <%# <div class="dropdown-center">
        <button class="btn btn-sm btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-filter"></i> Filter Books
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="#">Tile</a></li>
          <li><a class="dropdown-item" href="#">Author</a></li>
          <li><a class="dropdown-item" href="#">Genre</a></li>
        </ul>
      </div> %>
      <% if user_signed_in? %>
        <div> <% current_user.email %> <% current_user.id %> </div>
      <% end %>
    </div>
    <div class="width-large">
      <div class="grid" data-helper-target="mainContainer"></div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="width-large flex-row center-flex ">
  <div class="width-md-1 center-flex flex-col flex-gap">
    <div class="flex-row flex-space-between width-large">
      <%= link_to "Back to books", books_path, class: 'btn btn-secondary left-arrow' %>
      <H4>New book</H4>
    </div>
    <%= render "form", book: @book, is_edit: false %>
    <div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= render @book %>
<div>
  <% link_to "Edit this book", edit_book_path(@book) %>
  <% link_to "Back to books", books_path %>
  <% button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/books/uploads.html.erb
<div class="width-large flex-row center-flex">
  <div class="width-md-1 flex-col flex-gap align-flex-start">
    <div class="flex-row flex-space-between width-large">
      <%= link_to "New book", new_book_path, class: 'btn btn-sm btn-dark' %>
      <div class="dropdown-center">
        <button class="btn btn-sm btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-filter"></i> Filter Books
        </button>
        <ul class="dropdown-menu">
          <li> <%= link_to 'Not Sold', uploads_path(query: 'not-sold'), class:"dropdown-item" %> </li>
          <li> <%= link_to 'Sold out', uploads_path(query: 'sold'), class:"dropdown-item" %> </li>
          <li> <%= link_to 'All Books', uploads_path(query: 'all-books'), class:"dropdown-item" %> </li>
        </ul>
      </div>
    </div>
    <div class="width-large x-scrollable">
      <%= turbo_frame_tag 'book-table' do %>
        <%= render 'table', books: @books %>
      <% end %>
    </div>
  </div>
</div>

app/views/cart/_cart.html.erb
<br>
<p> <%= book.id %> </p>
<br>
<p> <%= book.user_id %> </p>
<br>
<p> <%= book.book_id %> </p>
<br>
<hr>

app/views/cart/_row.html.erb
<tr>
  <td>1</td>
  <td> <%= book.title %> </td>
  <td> <%= book.author %> </td>
  <td> <%= user.full_name %> </td>
  <td> <%= user.email %> </td>
  <td> <%= user.username %> </td>
</tr>

app/views/cart/buy_book.html.erb
<%= turbo_frame_tag "btn-change" do %>
  <span class="badge text-bg-success">Book is add in the cart</span>
  <% link_to 'Remove this book', return_book_path(@book), class: 'btn btn-success', data: { "turbo-method": :delete } %>
<% end %>

app/views/cart/index.html.erb
<div class="pad width-large flex-col flex-gap">
  <div> <%= link_to 'Sold Books', sold_path %> </div>
  <%= turbo_frame_tag 'sold-books' do %>
    <div class="width-large flex-col flex-gap">
      <% @carts.each do |cart| %>
        <%= render 'partials/card', book: cart.book %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/cart/remove_book.html.erb
<%= turbo_frame_tag "btn-change" do %>
  <%= link_to 'Buy this book', add_book_path(@book), class: 'btn btn-success' %>
<% end %>

app/views/cart/remove_book.turbo_stream.erb
<%= turbo_stream.replace 'sold-books' do %>
<% end %>

app/views/cart/sold.html.erb
<div class="width-large flex-row center-flex">
  <div class="width-md-1 flex-col flex-gap align-flex-start">
    <div class="flex-row flex-space-between width-large">
    </div>
    <div class="width-large x-scrollable">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Book Title</th>
            <th scope="col">Book Author</th>
            <th scope="col">Buyer Full Name</th>
            <th scope="col">Buyer Email</th>
            <th scope="col">Buyer Username</th>
          </tr>
        </thead>
        <tbody>
          <% @carts.each do |cart| %>
            <%= render 'row', book: cart.book, user: cart.user %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="nav-bar flex-row flex-gap center-flex-y pad">
  <div class="flex-row flex-gap center-flex-y" >
    <%= link_to "Five Books", root_path , class: "logo flex-row center-flex" %>
    <% if user_signed_in?  %>
      <div class="flex-row flex-gap">
        <a href="#" class="link"> <i class="bi bi-heart"></i> </a>
        <%= link_to uploads_path, class: 'link' do %>
          <i class="bi bi-book"></i>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="">
    <form action="" class="border flex-row search-container" method="get" data-helper-target="searchForm" >
      <input type="text" placeholder="Search Books.." data-helper-target="searchField">
      <button data-action="helper#search" > <svg xmlns="http://www.w3.org/2000/svg" height="30" viewBox="0 -960 960 960" width="30"><path d="M790.615-137.54 531.077-397.078q-29.848 26.414-69.61 40.707t-82.313 14.293q-101.873 0-172.436-70.514t-70.563-170.999q0-100.485 70.514-171.062 70.514-70.577 171.219-70.577 100.706 0 171.255 70.533 70.548 70.532 70.548 171.054 0 42.028-14.384 81.835-14.385 39.808-41.616 72.115l260.154 258.539-33.23 33.614ZM378.539-387.461q81.955 0 138.862-57.116 56.907-57.115 56.907-139.077 0-81.961-56.907-139.077-56.907-57.115-138.862-57.115-82.468 0-139.734 57.115-57.266 57.116-57.266 139.077 0 81.962 57.266 139.077 57.266 57.116 139.734 57.116Z"/></svg> </button>
    </form>
  </div>
  <% if user_signed_in?  %>
    <div class="flex-row flex-gap center-flex-y">
      <%# <a href="#" class="link" > <i class="bi bi-cart3"></i> </a> %>
      <%= link_to carts_path, class: 'link' do %>
        <i class="bi bi-cart3"></i>
      <% end %>
      <div class="btn-group">
        <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-person-fill"></i> User
        </button>
        <ul class="dropdown-menu">
          <%= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", data: { "turbo-method": :delete } %>
          <%= link_to "Edit User", edit_user_registration_path, class: "dropdown-item" %>
          <p class="dropdown-item"> <%= current_user.email %> </p>
        </ul>
      </div>
    </div>
  <% else %>
    <div class="flex-row flex-gap center-flex-y">
      <%= link_to "Sign In", new_user_session_path, class: 'link' %>
    </div>
  <% end %>
</nav>
<%#  %>
<nav class="nav-bar-small flex-col" data-controller="main" data-main-target="navBar">
  <div class="flex-row flex-space-between pad">
    <%= link_to "Five Books", root_path , class: "logo flex-row center-flex" %>
    <button class="header-toggler" data-action="main#toggleNavbar">
      <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="M120-240v-80h720v80H120Zm0-200v-80h720v80H120Zm0-200v-80h720v80H120Z"/></svg>
    </button>
  </div>
  <% if user_signed_in?  %>
    <div class="flex-col">
      <a href="#" class="link"> <i class="bi bi-heart"></i> <span>Favorite</span> </a>
      <%# <a href="#" class="link"> Uploads </a> %>
      <%= link_to uploads_path, class: 'link' do %>
        <i class="bi bi-book"></i> <span>My Books</span>
      <% end %>
    </div>
  <% else %>
    <div class="flex-row center-flex-y">
      <%= link_to "Sign In", new_user_session_path, class: 'link' %>
    </div>
  <% end %>
  <% if user_signed_in?  %>
    <div class="flex-col">
      <%= link_to carts_path, class: 'link' do %>
        <i class="bi bi-cart3"></i> <span> Carts </span>
      <% end %>
      <%# <a href="#" class="link" > <i class="bi bi-cart3"></i> <span> Carts </span> </a> %>
      <div class="pad">
        <div class="btn-group btn-width">
          <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-fill"></i> User
          </button>
          <ul class="dropdown-menu">
            <%= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", data: { "turbo-method": :delete } %>
            <%= link_to "Edit User", edit_user_registration_path, class: "dropdown-item" %>
            <p class="dropdown-item"> <%= current_user.email %> </p>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
  <div class="pad">
    <form action="" class="border flex-row search-container" method="get">
      <input type="text" placeholder="Search Books..">
      <button> <svg xmlns="http://www.w3.org/2000/svg" height="30" viewBox="0 -960 960 960" width="30"><path d="M790.615-137.54 531.077-397.078q-29.848 26.414-69.61 40.707t-82.313 14.293q-101.873 0-172.436-70.514t-70.563-170.999q0-100.485 70.514-171.062 70.514-70.577 171.219-70.577 100.706 0 171.255 70.533 70.548 70.532 70.548 171.054 0 42.028-14.384 81.835-14.385 39.808-41.616 72.115l260.154 258.539-33.23 33.614ZM378.539-387.461q81.955 0 138.862-57.116 56.907-57.115 56.907-139.077 0-81.961-56.907-139.077-56.907-57.115-138.862-57.115-82.468 0-139.734 57.115-57.266 57.116-57.266 139.077 0 81.962 57.266 139.077 57.266 57.116 139.734 57.116Z"/></svg> </button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Five Books</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "secondary_style", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <div class="flex-col height-body" data-controller="helper">
      <%= render 'layouts/navbar' %>
      <div class="pad height-main">
        <% if notice %>
          <div class="alert alert-secondary alert-dismissible fade show" role="alert">
            <%= notice %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
        <% if alert %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <%= alert %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
        <div class="width-large flex-row ">
          <%= yield %>
        </div>
      </div>
      <footer>
        LABEL
      </footer>
    </div>
  </body>
</html>

app/views/partials/_card.html.erb
<div id="<%= "#{dom_id(book)}_item" %>" class="">
  <div class="large-screen">
    <div class="width-md-2 flex-gap flex-row pad border-radius shadow">
      <div>
        <% if book.image.attached? %>
          <% if book.image.image? %>
            <%= image_tag book.image, class: 'image-size-small' %>
          <% end %>
        <% else %>
          <img class="image-size-small" src="https://images.template.net/174732/free-story-book-cover-template-edit-online.jpg" alt="">
        <% end %>
        <%# <img class="image-size-small" src="https://images.template.net/174732/free-story-book-cover-template-edit-online.jpg" alt=""> %>
      </div>
      <%# detail container %>
      <div class="flex-col pad flex-gap flex-1">
        <%# TITLE %>
        <div class="width-large flex-row flex-space-between">
          <h3> <%= book.title %> </h3>
          <%# <button class="btn btn-danger"> Return this book </button> %>
          <%= button_to "Return this book", return_book_path(book), method: :delete, class: 'btn btn-danger' %>
        </div>
        <span> <%= book.author %> </span>
        <span> <%= book.genre %> - <%= book.year.year %> </span>
        <span>
          <% if book.description.length >= 400 %>
            <%= book.description[0..400] %>...
          <% else %>
            <%= book.description %>
          <% end %>
        </span>
        <%# OTHER PART %>
      </div>
    </div>
  </div>
  <%# responsive screen %>
  <div class="small-screen">
    <div class="width-large flex-gap flex-col pad border-radius shadow">
      <div>
        <% if book.image.attached? %>
          <% if book.image.image? %>
            <%= image_tag book.image, class: 'image-size-small' %>
          <% end %>
        <% else %>
          <img class="image-size-small" src="https://images.template.net/174732/free-story-book-cover-template-edit-online.jpg" alt="">
        <% end %>
        <%# <img class="image-size-small width-large" src="https://images.template.net/174732/free-story-book-cover-template-edit-online.jpg" alt=""> %>
      </div>
      <%# detail container %>
      <div class="flex-col pad flex-gap ">
        <%# TITLE %>
        <div class="flex-col">
          <h3> <%= book.title %> </h3>
          <button class="btn btn-danger width-large"> Return this book </button>
        </div>
        <span> <%= book.author %> </span>
        <span> <%= book.genre %> - <%= book.year %> </span>
        <span>
          <% if book.description.length >= 400 %>
            <%= book.description[0..400] %>...
          <% else %>
            <%= book.description %>
          <% end %>
        </span>
        <%# OTHER PART %>
      </div>
    </div>
  </div>
</div>